
import { writeFileSync } from 'fs';
import bcrypt from 'bcryptjs';

const rawData = `
1 IOMOB  TESTE - fueZhej39xRE
2	ROTARY CLUB DE ARAUCÁRIA	UTeziAj0QeX6
3	ROTARY CLUB DE ARAUCÁRIA PASSAUNA	D6XzCPi7P3cA
4	ROTARY CLUB DE BOCAIUVA DO SUL	2stWmdTamzy9
5	ROTARY CLUB DE CAMPO LARGO	WFxPRXHV2Fkb
6	ROTARY CLUB DE CAMPO MAGRO	5YTcPpXEtGFE
8	ROTARY CLUB DE CAMPO DO TENENTE	tLUXlzr2scRW
9	ROTARY CLUB DE CARAMBEÍ	Z7osj4KYcwUz
10	ROTARY CLUB DE CASTRO	Xv2n51RzAZlK
11	ROTARY CLUB DE CURITIBA	lygSvgnxcYC6
12	ROTARY CLUB DE CURITIBA ALTO DA GLÓRIA	1thgFKuFgoKE
13	ROTARY CLUB DE CURITIBA AVENIDA DAS TORRES	XRdac4ob6th7
14	ROTARY CLUB DE CURITIBA BATEL	k0J4RmWPuDC9
15	ROTARY CLUB DE CURITIBA BOM RETIRO	8M7q3TtIMOmd
16	ROTARY CLUB DE CURITIBA CHAMPAGNAT	e1RI4Xrdn6wZ
17	ROTARY CLUB DE CURITIBA CIDADE ECOLÓGICA	CtTDbAfVjkuo
18	ROTARY CLUB DE CURITIBA CIDADE INDUSTRIAL	PKgDSWSbZzBC
19	ROTARY CLUB DE CURITIBA CIQUENTENÁRIO	QWVpE8iYrWfM
20	ROTARY CLUB DE CURITIBA CORPORATIVO SANEPAR	TfQdjsNVpyly
21	ROTARY CLUB DE CURITIBA CRISTO REI	0p2a1OpgClOl
22	ROTARY CLUB DE CURITIBA CRUZEIRO DO SUL	UROLvHUFb931
23	ROTARY CLUB DE CURITIBA FRATERNA	Pjp234x6ZJHA
24	ROTARY CLUB DE CURITIBA GRALHA AZUL	3ffCcHuz87BY
25	ROTARY CLUB DE CURITIBA GUABIROTUBA	xJD5K3AtOBAL
26	ROTARY CLUB DE CURITIBA III MILÊNIO	QhZSiShiNsCW
27	ROTARY CLUB DE CURITIBA INCLUSÃO MARIA DE LOURDES BARBALHO PIMENTEL	tKOwAUeqtvXw
28	ROTARY CLUB DE CURITIBA LESTE	f9yNqQj52QfZ
29	ROTARY CLUB DE CURITIBA MARUMBY	HJ5VwftKcVpQ
30	ROTARY CLUB DE CURITIBA MERCÊS	cq1EYtpIc4Pv
31	ROTARY CLUB DE CURITIBA NORTE	SL5vaBAm8v5y
32	ROTARY CLUB DE CURITIBA OESTE	OaEBU8UwDFNV
33	ROTARY CLUB DE CURITIBA ÓPERA DE ARAME	cYtuENmsGcV8
34	ROTARY CLUB DE CURITIBA PARQUE BARIGUI	cVZ4g8DtIsDw
35	ROTARY CLUB DE CURITIBA PORTÃO	V8S9gLadZF9w
36	ROTARY CLUB DE CURITIBA REBOUÇAS	1DFURXB7ecw5
37	ROTARY CLUB DE CURITIBA SANTA FELICIDADE	ncc5kpGwgoR7
38	ROTARY CLUB DE CURITIBA SÃO BRAZ	vYIKqFlSpc1e
39	ROTARY CLUB DE CURITIBA SÍTIO CERCADO	UvsUb9ELLaBi
40	ROTARY CLUB DE CURITIBA SUL	7IPilgSj4214
41	ROTARY CLUB DE FAZENDA RIO GRANDE	uRRzmvPADMB8
42	ROTARY CLUB DE GUARATUBA	CynLIa1Fg9Us
43	ROTARY CLUB DE INÁCIO MARTINS	Ed2JWDWL9It2
44	ROTARY CLUB DE IRATI	9NBpVSBGQ7Vj
45	ROTARY CLUB DE JAGUARIÁIVA	RGPVnVScpUmv
46	ROTARY CLUB DE MANDIRITUBA	vpNIlrm2bqOY
47	ROTARY CLUB DE MATINHOS	QW2lGeHBAYuz
48	ROTARY CLUB DE MORRETES	klil4JMJXRS0
49	ROTARY CLUB DE PALMEIRA	rMSLAOcShPYo
50	ROTARY CLUB DE PARANAGUÁ	FSbSgtBnXrZ5
51	ROTARY CLUB DE PARANAGUÁ ROCIO	CIDKGoU5sLrM
52	ROTARY CLUB DE PINHAIS	1sNaDdx60ndH
53	ROTARY CLUB DE PINHAIS - PARQUE DAS ÁGUAS	64hEBDc8eCkC
54	ROTARY CLUB DE PINHAIS - ALPHAVILLE GRACIOSA	2MnI9jrzydNI
55	ROTARY CLUB DE PIRAÍ DO SUL	ZXrdnAPimKhT
56	ROTARY CLUB DE PIRAQUARA	0OyP6w0g2E5X
57	ROTARY CLUB DE PONTA GROSSA	SWgauOi27ffR
58	ROTARY CLUB DE PONTA GROSSA ALAGADOS	54NDIEHJwein
59	ROTARY CLUB DE PONTA GROSSA CAMPOS GERAIS	fgF5V2xVaktD
60	ROTARY CLUB DE PONTA GROSSA CENTENÁRIO	ctrVoa3cYwCM
61	ROTARY CLUB DE PONTA GROSSA LAGOA DOURADA	EQj2idECRbpA
62	ROTARY CLUB DE PONTA GROSSA OESTE	0Bnni6AWoVPD
63	ROTARY CLUB DE PONTA GROSSA SABARÁ	4K9gczztAa9w
64	ROTARY CLUB DE PONTA GROSSA UVARANAS	pN04s7w802Ih
65	ROTARY CLUB DE PONTA GROSSA VILA VELHA	qe35D5fMd31e
66	ROTARY CLUB DE PONTAL DO PARANÁ UNIÃO	wVh52o2w5BgO
67	ROTARY CLUB DE PRUDENTÓPOLIS CACHOEIRA	tbCrzESgrm1I
68	ROTARY CLUB DE QUATRO BARRAS GRACIOSA	xYvOzFrJZLqC
69	ROTARY CLUB DE QUITANDINHA INOVAÇÃO	kA4oGlX6KUog
70	ROTARY CLUB DE RESERVA	kmSUGGUb0kg4
71	ROTARY CLUB DE RIO NEGRO	jVehwpauzNXh
72	ROTARY CLUB DE RIO NEGRO RIOMAFRA	yaQqhB1qHCLl
73	ROTARY CLUB DE SÃO JOSÉ DOS PINHAIS	qZnGo9STv7iW
74	ROTARY CLUB DE SÃO JOSÉ DOS PINHAIS AFONSO PENA	LvJk8cXS2bwS
75	ROTARY CLUB DE SÃO JOSÉ DOS PINHAIS COLÔNIA MURICI	qMQBkeljdbMf
76	ROTARY CLUB DE SÃO JOSÉ DOS PINHAIS IGUAÇÚ	UlD84FC9XoBL
77	ROTARY CLUB DE SÃO MATEUS SUL	QzOtQUA45Gse
78	ROTARY CLUB SÃO MATEUS DO SUL XISTO IGUAÇÚ	qn2iPyaur4tM
79	ROTARY CLUB DE TEIXEIRA SOARES	TJ29fK6F994E
80	ROTARY CLUB TIJUCAS DO SUL	0HquRANsQoDZ
81	ROTARY CLUB SATÉLITE CURITIBA PARQUE BARIGUI BORDA DO CAMPO	kYnGUldKTqvz
82	ROTARY CLUB SATÉLITE PONTA GROSSA SABARÁ INTEGRAÇÃO	go7CQjN2enHn
83	ROTARY CLUB SATÉLITE DE CURITIBA III MILÊNIO - TELEMACO BORBA RENOVAÇÃO	uzzQ3sDJYHw2
84	ROTARY CLUB SATÉLITE DE PONTA GROSSA UVARANAS - NOVA VISÃO	XcfugXfJjJwW
85	ROTARY CLUB SATÉLITE CURITIBA PARQUE BARIGUI CAMPO LARGO CAPITAL DA PORCELANA	NO7eBbyQzFNg
86	ROTARY CLUB SATÉLITE ANTONINA CAIÇARA	XgznlJ4D818N
87	ROTARACT CLUB BEYOND BORDERS	luP3M0xW6UP7
88	ROTARACT CLUB DE CURITIBA AVENIDA DAS TORRES	gwPkFvtjljsJ
89	ROTARACT CLUB DE CURITIBA BOM RETIRO	ld6xcJQPJgd4
90	ROTARACT CLUB DE CURITIBA CEU	9Dbwly0bvwxD
91	ROTARACT CLUB DE CURITIBA GRALHA AZUL	hK7BYcw2kqMO
92	ROTARACT CLUB DE CURITIBA III MILENIO	j0bgZolhzAPp
93	ROTARACT CLUB DE CURITIBA LESTE	VEklwS0AQurf
94	ROTARACT CLUB DE CURITIBA OESTE	IONDIyOfPXHY
95	ROTARACT CURITIBA PARQUE BARIGUI	wDAsl0dr8Qbv
96	ROTARACT CLUB DE CURITIBA REBOUÇAS	9CAAjX9CyHmm
97	ROTARACT CLUB CURITIBA UFPR	BLP71wOpJcOW
98	ROTARACT CLUB DE GUARATUBA	tBmZpGblEszt
99	ROTARACT MERCÊS	ahIAPX5VJCN6
100	ROTARACT CLUB DE PONTA GROSSA ALAGADOS	ZU7iVSlzOQZC
`;

const lines = rawData.trim().split('\n');
const results = [];

for (const line of lines) {
  // Try tab separation first, then hyphen
  let name, password;
  if (line.includes('\t')) {
    const parts = line.split('\t');
    name = parts[1].trim();
    password = parts[2].trim();
  } else if (line.includes(' - ')) {
    const parts = line.split(' - ');
    const namePart = parts[0].trim();
    // Remove the number at the beginning
    name = namePart.replace(/^\d+\s+/, '').trim();
    password = parts[1].trim();
  }

  if (name && password) {
    const hash = bcrypt.hashSync(password, 10);
    results.push({ name, password, hash });
  }
}

// Generate CSV
const csv = "Nome do Clube,Senha Temporária\n" + 
  results.map(r => `"${r.name}",${r.password}`).join("\n");
writeFileSync('scripts/clubs_passwords.csv', csv);

// Generate SQL (with initial_password column for admin reference)
const sql = results.map(r => 
  `INSERT INTO public.clubs (name, password_hash, initial_password) VALUES ('${r.name.replace(/'/g, "''")}', '${r.hash}', '${r.password}') ON CONFLICT (name) DO UPDATE SET password_hash = EXCLUDED.password_hash, initial_password = EXCLUDED.initial_password;`
).join("\n");
writeFileSync('scripts/seed_clubs.sql', sql);

console.log(`Seed files updated for ${results.length} clubs.`);
