// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Helper to check for club token on startup
if (typeof window !== 'undefined') {
  const clubToken = localStorage.getItem("solidario_club_token");
  if (clubToken) {
    supabase.auth.getSession().then(({ data: { session } }) => {
      if (!session) {
        supabase.auth.setSession({
          access_token: clubToken,
          refresh_token: "",
        });
      }
    });
  }
}